# Λίστα με objects που περιέχει το k08.a library
k08.a_OBJS =									\
	$(MODULES)/ABTrees/AB_Node.o				\
	$(MODULES)/ABTrees/AB_Tree.o				\
	$(MODULES)/ABTrees/B_Tree.o					\
	$(MODULES)/BinaryHeap/BinaryHeap.o	        \
	$(MODULES)/BinaryTree/BinarySearchTree.o	\
	$(MODULES)/BinaryTree/BinaryTree.o			\
	$(MODULES)/BinaryTree/CompleteBinaryTree.o	\
	$(MODULES)/BinaryTree/Treenode.o			\
	$(MODULES)/Bitmap/Bitmap.o					\
	$(MODULES)/HashTable/HashTable.o			\
	$(MODULES)/HashTable/HashTableEntry.o		\
	$(MODULES)/InvertedIndex/InvertedIndex.o	\
	$(MODULES)/List/List.o						\
	$(MODULES)/List/Listnode.o					\
	$(MODULES)/Pairs/ComplexItem.o				\
	$(MODULES)/Pairs/PairBool.o					\
	$(MODULES)/Pairs/PairInt.o					\
	$(MODULES)/Queue/Queue.o					\
	$(MODULES)/RedBlackTree/RedBlackTree.o					

# Ο βασικός κορμός του Makefile
include ../common.mk
