# Κάνοντας compile το <foo>_test.cpp με μια υλοποίηση <foo>.cpp του
# συγκεκριμένου τύπου, παράγουμε ένα tets για την υλοποίηση αυτή.

ABTrees_ABTree_test_OBJS = ABTree_test.o $(MODULES)/ABTrees/AB_Tree.o $(MODULES)/ABTrees/AB_Node.o $(MODULES)/List/List.o $(MODULES)/List/Listnode.o $(MODULES)/Pairs/PairInt.o $(MODULES)/Pairs/ComplexItem.o

ABTrees_BTree_test_OBJS = BTree_test.o  $(MODULES)/ABTrees/B_Tree.o $(MODULES)/ABTrees/AB_Tree.o $(MODULES)/ABTrees/AB_Node.o $(MODULES)/List/List.o $(MODULES)/List/Listnode.o $(MODULES)/Pairs/PairInt.o $(MODULES)/Pairs/ComplexItem.o

BinaryHeap_BinaryHeap_test_OBJS = BinaryHeap_test.o $(MODULES)/BinaryHeap/BinaryHeap.o $(MODULES)/BinaryTree/CompleteBinaryTree.o $(MODULES)/BinaryTree/BinaryTree.o $(MODULES)/BinaryTree/Treenode.o $(MODULES)/Pairs/ComplexItem.o 

BinaryTree_BinarySearchTree_test_OBJS = BinarySearchTree_test.o $(MODULES)/BinaryTree/BinarySearchTree.o $(MODULES)/BinaryTree/BinaryTree.o $(MODULES)/BinaryTree/Treenode.o $(MODULES)/Pairs/ComplexItem.o 

BinaryTree_BinaryTree_test_OBJS = BinaryTree_test.o $(MODULES)/BinaryTree/BinaryTree.o $(MODULES)/BinaryTree/Treenode.o $(MODULES)/Pairs/ComplexItem.o 

BinaryTree_CompleteBinaryTree_test_OBJS = CompleteBinaryTree_test.o $(MODULES)/BinaryTree/CompleteBinaryTree.o $(MODULES)/BinaryTree/BinaryTree.o $(MODULES)/BinaryTree/Treenode.o $(MODULES)/Pairs/ComplexItem.o

Bitmap_Bitmap_test_OBJS = Bitmap_test.o $(MODULES)/Bitmap/Bitmap.o

HashTable_HashTable_test_OBJS = HashTable_test.o $(MODULES)/HashTable/HashTable.o $(MODULES)/HashTable/HashTableEntry.o $(MODULES)/Bitmap/Bitmap.o $(MODULES)/List/List.o $(MODULES)/List/Listnode.o $(MODULES)/Pairs/ComplexItem.o

InvertedIndex_InvertedIndex_test_OBJS = InvertedIndex_test.o $(MODULES)/InvertedIndex/InvertedIndex.o $(MODULES)/RedBlackTree/RedBlackTree.o $(MODULES)/Pairs/PairBool.o $(MODULES)/BinaryTree/BinarySearchTree.o $(MODULES)/BinaryTree/BinaryTree.o $(MODULES)/BinaryTree/Treenode.o $(MODULES)/Pairs/ComplexItem.o 

List_List_test_OBJS = List_test.o $(MODULES)/List/List.o $(MODULES)/List/Listnode.o

Queue_Queue_test_OBJS = Queue_test.o $(MODULES)/Queue/Queue.o $(MODULES)/List/List.o $(MODULES)/List/Listnode.o

RedBlackTree_RedBlackTree_test_OBJS = RedBlackTree_test.o $(MODULES)/RedBlackTree/RedBlackTree.o $(MODULES)/Pairs/PairBool.o $(MODULES)/BinaryTree/BinarySearchTree.o $(MODULES)/BinaryTree/BinaryTree.o $(MODULES)/BinaryTree/Treenode.o $(MODULES)/Pairs/ComplexItem.o 

# Ο βασικός κορμός του Makefile
include ../common.mk